#!/bin/bash

# ==========================================
# Linux Security Compliance Auditor
# Main Engine
# ==========================================

# Locate project directory (works from any cwd)
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# ==========================================
# 1. Initialize Counters
# ==========================================

PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

REPORT_DIR="$SCRIPT_DIR/reports"
REPORT_FILE="$REPORT_DIR/report.html"

mkdir -p "$REPORT_DIR"

cat > "$REPORT_FILE" <<'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Linux Security Audit Report</title>

<style>
body {
    font-family: Arial, sans-serif;
    background: #f4f6f9;
    margin: 30px;
    color: #222;
}
h1 { color: #172554; }
.summary {
    background: white;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 20px;
}
table {
    width: 100%;
    border-collapse: collapse;
    background: white;
}
th, td {
    padding: 12px;
    border: 1px solid #ddd;
    text-align: left;
}
th { background: #172554; color: white; }
.PASS { color: green; font-weight: bold; }
.FAIL { color: red; font-weight: bold; }
.WARN { color: #b45309; font-weight: bold; }
</style>
</head>

<body>
<h1>Linux Security Compliance Audit</h1>
<p>Generated by Linux Security Compliance Auditor</p>

<table>
<thead>
<tr>
<th>Check</th>
<th>Category</th>
<th>Severity</th>
<th>Status</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
EOF

html_escape() {
    local value="$1"

    value=${value//&/\&amp;}
    value=${value//</\&lt;}
    value=${value//>/\&gt;}
    value=${value//\"/\&quot;}
    value=${value//\'/\&#39;}

    printf '%s' "$value"
}


# ==========================================
# 2. Common Function to Display Check Results
# ==========================================

check_result() {
    local name="$1"
    local category="$2"
    local severity="$3"
    local status="$4"
    local explanation="$5"

    case "$status" in
        PASS)
            PASS_COUNT=$((PASS_COUNT + 1))
            ;;
        FAIL)
            FAIL_COUNT=$((FAIL_COUNT + 1))
            ;;
        WARN)
            WARN_COUNT=$((WARN_COUNT + 1))
            ;;
        *)
            echo "ERROR: Invalid status '$status' for check '$name'"
            return 1
            ;;
    esac
    printf '<tr><td>%s</td><td>%s</td><td>%s</td><td class="%s">%s</td><td>%s</td></tr>\n' \
        "$(html_escape "$name")" \
        "$(html_escape "$category")" \
        "$(html_escape "$severity")" \
        "$(html_escape "$status")" \
        "$(html_escape "$status")" \
        "$(html_escape "$explanation")" \
        >> "$REPORT_FILE"

    echo "----------------------------------------"
    echo "Check       : $name"
    echo "Category    : $category"
    echo "Severity    : $severity"
    echo "Status      : $status"
    echo "Explanation : $explanation"
    echo "----------------------------------------"
}

# ==========================================
# 3. Load All Security Check Modules
# ==========================================

MODULES=(
    "checks/ssh_checks.sh"
    "checks/user_checks.sh"
    "checks/file_checks.sh"
    "checks/network_checks.sh"
    "checks/service_checks.sh"
    "checks/logging_checks.sh"
    "checks/kernel_checks.sh"
    "checks/update_checks.sh"
)

echo ""
echo "========================================"
echo "    LINUX SECURITY COMPLIANCE AUDITOR"
echo "========================================"
echo ""

for module in "${MODULES[@]}"; do
    if [[ -f "$SCRIPT_DIR/$module" ]]; then
        source "$SCRIPT_DIR/$module"
    else
        echo "ERROR: Missing module: $module"
        echo "Audit cannot continue with missing modules."
        exit 1
    fi
done

# ==========================================
# 4. Execute SSH Checks
# ==========================================

echo ""
echo "========== SSH SECURITY CHECKS =========="

check_root_login
check_empty_passwords
check_ssh_service

# ==========================================
# 5. Execute User & Password Checks
# ==========================================

echo ""
echo "======= USER & PASSWORD CHECKS =========="

check_password_expiry
check_root_uid
check_sudo_access

# ==========================================
# 6. Execute File Permission Checks
# ==========================================

echo ""
echo "======= FILE PERMISSION CHECKS =========="

check_passwd_permissions
check_shadow_permissions
check_group_permissions
check_gshadow_permissions

# ==========================================
# 7. Execute Firewall & Network Checks
# ==========================================

echo ""
echo "======= NETWORK SECURITY CHECKS ========="

check_firewall
check_listening_ports
check_ip_forwarding

# ==========================================
# 8. Execute Service Security Checks
# ==========================================

echo ""
echo "======= SERVICE SECURITY CHECKS ========="

check_failed_services
check_docker_service
check_unnecessary_services

# ==========================================
# 9. Execute Logging & Auditing Checks
# ==========================================

echo ""
echo "======= LOGGING & AUDITING CHECKS ========"

check_journald
check_auth_log
check_auditd

# ==========================================
# 10. Execute Kernel Hardening Checks
# ==========================================

echo ""
echo "========= KERNEL HARDENING CHECKS ========"

check_aslr
check_core_dumps
check_suid_files

# ==========================================
# 11. Execute Updates & Patching Checks
# ==========================================

echo ""
echo "========= UPDATE SECURITY CHECKS ========="

check_pending_updates
check_apt_service

# ==========================================
# 12. Compliance Score & Final Summary
# ==========================================

show_compliance_score() {

    local total
    local score

    total=$((PASS_COUNT + FAIL_COUNT + WARN_COUNT))

    echo ""
    echo "========================================"
    echo "          COMPLIANCE SUMMARY"
    echo "========================================"

    if [[ "$total" -eq 0 ]]; then
        echo "No checks were executed."
        return
    fi

    # PASS = 100, WARN = 50, FAIL = 0
    score=$(( (PASS_COUNT * 100 + WARN_COUNT * 50) / total ))

    echo "Total Checks : $total"
    echo "PASS         : $PASS_COUNT"
    echo "FAIL         : $FAIL_COUNT"
    echo "WARN         : $WARN_COUNT"
    echo "Score        : $score / 100"

    if [[ "$score" -ge 80 ]]; then
        echo "Rating       : Good"
    elif [[ "$score" -ge 50 ]]; then
        echo "Rating       : Needs Improvement"
    else
        echo "Rating       : Poor"
    fi

    echo "========================================"
}

show_compliance_score
TOTAL=$((PASS_COUNT + FAIL_COUNT + WARN_COUNT))

if [ "$TOTAL" -gt 0 ]; then
    SCORE=$(( (PASS_COUNT * 100 + WARN_COUNT * 50) / TOTAL ))
else
    SCORE=0
fi

cat >> "$REPORT_FILE" <<EOF
</tbody>
</table>

<div class="summary">
<h2>Compliance Summary</h2>
<p><strong>Total Checks:</strong> $TOTAL</p>
<p><strong>PASS:</strong> $PASS_COUNT</p>
<p><strong>FAIL:</strong> $FAIL_COUNT</p>
<p><strong>WARN:</strong> $WARN_COUNT</p>
<h2>Compliance Score: $SCORE / 100</h2>
</div>

</body>
</html>
EOF

echo "HTML report generated: $REPORT_FILE"

echo ""
echo "Audit completed."
